# security_config.yaml
security:
  enable_safety_checks: true
  max_execution_time: 300  # Sekunden
  max_memory_usage: 104857600  # Bytes (100MB)
  max_recursion_depth: 100
  backup_interval: 3600  # Sekunden
  fallback_enabled: true
  alert_threshold: 0.8
  monitoring_enabled: true

fallback:
  strategies:
    - minimal_state
    - previous_version
    - safe_defaults
    - emergency_mode
  timeout: 60
  retry_attempts: 3

safety:
  checks:
    - code_validation
    - resource_monitoring
    - execution_timeout
    - integrity_check
    - permission_verification