global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ki_self_sustain_backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/api/ai/metrics'
    scrape_interval: 30s

  - job_name: 'flowise'
    static_configs:
      - targets: ['flowise:3000']
    scrape_interval: 30s

  - job_name: 'llm_service'
    static_configs:
      - targets: ['llm_service:11434']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

